apiVersion: skaffold/v4beta8
kind: Config
build:
  local:
    push: false # don't push to docker hub automatically
  artifacts: # what part of our project skaffold needs to maintain
    - image: kliao36/blog-client
      context: blog-client
      sync:
        manual:
          - src: 'src/**/*.js' # if something not a js file is changed, the whole image is rebuilt by Skaffold
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kliao36/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kliao36/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kliao36/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kliao36/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: kliao36/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/* # ensure we create/delete all objects in the directory
deploy: # Deploy with kubectl
  kubectl: {}